version: "3"

services: 
 app_ci:
  labels:
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host(`metadevops.teladelogin.herokuapp.com`)"

 reverse-proxy:
  image: "traefik:v2.4"
  command: "--api --providers.docker.exposedbydefault=false" 
  ports: 
    - "80:80"
    - "8080:8080"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro" 