version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest 
    steps:
      - checkout
      - run:
          name: "Test Node"
          command: npm install 
      - run:
          name: "Test Jest"
          command: test

workflows:
  build-tests-deploy:
    jobs:
      - build     
